---

apps:
  - domain: localhost:3001
    fullDomainURL: http://localhost:3001
    fusionAuth:
      internalHostUrl: http://fusionauth:9011
      apiKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      appID: b0a0f0ab-64ad-4e50-9907-d06dd8901155
      tenantID: 0483de08-d073-4f4c-b49e-0cfbbe0e2808
    jwt:
      cookieDomain: "localhost"
      cookieMaxAgeSeconds: 3600
      cookieSetSecure: true
      cookieName: "s"
    stripe:
      publicKey: pk_test_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      secretKey: sk_test_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      paymentSuccessURL: http://localhost:3001/welcome
      paymentCancelURL: http://localhost:3001/welcome
      products:
        - productId: prod_xxxxxxxxxxxxxx # a subscription in Stripe
          priceIds:
            - price_xxxxxxxxxxxxxxxxxxxxxxxx # a pricing option for the subscription in Stripe
    apiKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx # MUST BE UNIQUE PER APP

global:
  bindAddr: 0.0.0.0
  bindPort: 8080
  bindPortExternal: 8080
